name: Elixir CI

on: push

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        # https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        include:
          # Newest supported Elixir/Erlang pair.
          - elixir: '1.16'
            otp: '26.0'

          # One version before the last supported one.
          - elixir: '1.15'
            otp: '24.0'

          # Oldest supported Elixir/Erlang pair.
          - elixir: '1.12'
            otp: '22.0'
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-elixir-${{ steps.beam.outputs.elixir-version }}-erlang-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-elixir-${{ steps.beam.outputs.elixir-version }}-erlang-${{ steps.beam.outputs.otp-version }}-
          path: |
            deps
            _build

      - run: mix deps.get
      - run: mix compile
      - run: mix test
